test_average (__main__.TestExercice) ... ok
test_square (__main__.TestExercice) ... ok
test_square_root (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... ok
test_to_degrees (__main__.TestExercice) ... FAIL
test_to_farenheit (__main__.TestExercice) ... ok
test_to_radians (__main__.TestExercice) ... ok

======================================================================
FAIL: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 86, in test_to_degrees
    'Mauvais calcul de radians -> degres'
AssertionError: Lists differ: [(0.03490658503988659, 2.0943951023931953, [198 chars]508)] != [(79.0980174562859, 5.881047377154118, 29.6[197 chars]998)]

First differing element 0:
(0.03490658503988659, 2.0943951023931953, 5.663706143591716)
(79.0980174562859, 5.881047377154118, 29.612494192724625)

- [(0.03490658503988659, 2.0943951023931953, 5.663706143591716),
-  (-0.06981317007977318, 55.81120979521361, 48.67258771281641),
-  (0.08726646259971647, 5.235987755982989, 14.15926535897933),
-  (0.07138396640656808, 4.283037984394085, 16.98227906364508)]
+ [(79.0980174562859, 5.881047377154118, 29.612494192724625),
+  (-278.1960349125718, 48.23790524569176, 0.7750116145507491),
+  (257.74504364071475, -15.297381557114704, 44.031235481811564),
+  (213.95544569810457, -2.673258113725865, 23.057550624127998)] : Mauvais calcul de radians -> degres

----------------------------------------------------------------------
Ran 7 tests in 0.003s

FAILED (failures=1)
